export type PlaceCategory =
  | "home"
  | "class"
  | "food"
  | "study"
  | "transit"
  | "shopping"
  | "service"
  | "attraction"
  | "landmark";

export type PlaceArea =
  | "west"
  | "east"
  | "ninth"
  | "essentials"
  | "durham"
  | "triangle"
  | "travel";

export type PlaceSource = {
  label: string;
  url: string;
  checkedAt: string;
};

export type Place = {
  id: string;
  name: string;
  shortName: string;
  category: PlaceCategory;
  categoryLabel: string;
  area?: PlaceArea;
  coordinates: [number, number];
  room?: string;
  address?: string;
  summary: string;
  facts: string[];
  source: PlaceSource;
  confidence: "verified" | "cross-checked" | "review";
  markerLabel: string;
  previewEmoji?: string;
  shuttle?: {
    route: string;
    summary: string;
    liveUrl: string;
  };
  links?: Array<{ label: string; url: string }>;
};

export type ShuttleStop = {
  id: string;
  name: string;
  shortName: string;
  area: PlaceArea;
  coordinates: [number, number];
  stopCode?: string;
};

export const SHUTTLE_ROUTE_NAME = "CSF：C1–Swift Avenue Shuttle";

export const SHUTTLE_STOPS: ShuttleStop[] = [
  {
    id: "east-campus-statue-stop",
    name: "East Campus Statue",
    shortName: "East Campus Statue",
    area: "east",
    coordinates: [36.0052024856, -78.9147518322],
  },
  {
    id: "blue-light-shuttle-stop",
    name: "The Blue Light Living",
    shortName: "Blue Light Stop",
    area: "east",
    coordinates: [36.005898, -78.92179],
  },
  {
    id: "swift-300-shuttle-stop",
    name: "Swift Ave at 300 Swift",
    shortName: "300 Swift Stop",
    area: "east",
    coordinates: [36.0027490109, -78.9215145362],
  },
  {
    id: "swift-campus-west-stop",
    name: "Swift at Campus Drive",
    shortName: "Swift / Campus W",
    area: "east",
    coordinates: [36.00012, -78.923389],
  },
  {
    id: "nasher-westbound-stop",
    name: "Campus Dr at Nasher Westbound",
    shortName: "Nasher Westbound",
    area: "west",
    coordinates: [36.000204, -78.926926],
  },
  {
    id: "anderson-westbound-stop",
    name: "Campus Dr at Anderson",
    shortName: "Anderson Westbound",
    area: "west",
    coordinates: [36.000055, -78.93004],
  },
  {
    id: "admissions-westbound-stop",
    name: "Campus Dr at Admissions Westbound",
    shortName: "Admissions Westbound",
    area: "west",
    coordinates: [35.999146, -78.933243],
  },
  {
    id: "west-campus-chapel-stop",
    name: "West Campus Chapel",
    shortName: "West Chapel Stop",
    area: "west",
    coordinates: [36.000953, -78.938252],
    stopCode: "12018",
  },
  {
    id: "chapel-circle-eastbound-stop",
    name: "Campus Dr at Chapel Circle Eastbound",
    shortName: "Chapel Circle E",
    area: "west",
    coordinates: [35.999056, -78.933058],
    stopCode: "12015",
  },
  {
    id: "anderson-eastbound-stop",
    name: "Campus Dr at Anderson St Eastbound",
    shortName: "Anderson Eastbound",
    area: "west",
    coordinates: [36.000025, -78.930371],
    stopCode: "12012",
  },
  {
    id: "nasher-eastbound-stop",
    name: "Campus Dr at Nasher Eastbound",
    shortName: "Nasher Eastbound",
    area: "west",
    coordinates: [35.999812, -78.928486],
  },
  {
    id: "swift-campus-eastbound-stop",
    name: "Campus Dr at Swift Ave Eastbound",
    shortName: "Swift / Campus E",
    area: "east",
    coordinates: [35.999964, -78.923602],
  },
  {
    id: "swift-caswell-eastbound-stop",
    name: "Swift Avenue at Caswell Pl Eastbound",
    shortName: "Swift / Caswell",
    area: "east",
    coordinates: [36.002669, -78.921374],
  },
];

// Duke Transit GTFS route shape, simplified from 473 to 68 points for the map.
export const SHUTTLE_ROUTE_SHAPE: [number, number][] = [
  [36.00518, -78.91476],
  [36.00343, -78.91479],
  [36.00557, -78.91895],
  [36.00598, -78.91983],
  [36.00639, -78.92128],
  [36.00654, -78.922],
  [36.00655, -78.92227],
  [36.0063, -78.92229],
  [36.00606, -78.92239],
  [36.00578, -78.92108],
  [36.00538, -78.91989],
  [36.00509, -78.91993],
  [36.00473, -78.92007],
  [36.00347, -78.9209],
  [35.99999, -78.92341],
  [36.00036, -78.92521],
  [36.00039, -78.92557],
  [36.00032, -78.92633],
  [35.99998, -78.92756],
  [35.99987, -78.92834],
  [35.99988, -78.92893],
  [36.00007, -78.93049],
  [36.00006, -78.93088],
  [36.00001, -78.93113],
  [35.99986, -78.9315],
  [35.99919, -78.93281],
  [35.99908, -78.93322],
  [35.99901, -78.93386],
  [35.99912, -78.93393],
  [35.99916, -78.93402],
  [35.99916, -78.93414],
  [35.99908, -78.93426],
  [36.0003, -78.93689],
  [36.00062, -78.93754],
  [36.0008, -78.93752],
  [36.00106, -78.93805],
  [36.00091, -78.93824],
  [36.00073, -78.93825],
  [36.00052, -78.93776],
  [36.00054, -78.93764],
  [36.00062, -78.93754],
  [35.99908, -78.93426],
  [35.99902, -78.93429],
  [35.99891, -78.93427],
  [35.99882, -78.9341],
  [35.99885, -78.93396],
  [35.99893, -78.93388],
  [35.99901, -78.93386],
  [35.99905, -78.93341],
  [35.99919, -78.93281],
  [35.99986, -78.9315],
  [36.00001, -78.93113],
  [36.00006, -78.93088],
  [36.00007, -78.93049],
  [35.99988, -78.92893],
  [35.99987, -78.92834],
  [35.99998, -78.92756],
  [36.00032, -78.92633],
  [36.00039, -78.92557],
  [36.00036, -78.92521],
  [35.99999, -78.92341],
  [36.00347, -78.9209],
  [36.00473, -78.92007],
  [36.00509, -78.91993],
  [36.00598, -78.91983],
  [36.00557, -78.91895],
  [36.00343, -78.91479],
  [36.00518, -78.91476],
];

export const CATEGORY_META: Record<
  PlaceCategory,
  { label: string; color: string; soft: string }
> = {
  home: { label: "宿舍", color: "#d83b3e", soft: "#fff0ef" },
  class: { label: "上课", color: "#6755d9", soft: "#f1efff" },
  food: { label: "餐饮", color: "#c36b14", soft: "#fff4e6" },
  study: { label: "自习", color: "#1769aa", soft: "#eaf4ff" },
  transit: { label: "交通", color: "#007a5e", soft: "#e7f7f2" },
  shopping: { label: "购物", color: "#a14d87", soft: "#fbeefa" },
  service: { label: "服务", color: "#516170", soft: "#edf1f4" },
  attraction: { label: "游览", color: "#2f7d32", soft: "#eaf7e9" },
  landmark: { label: "地标", color: "#0f7b6c", soft: "#e8f7f2" },
};

export const AREA_META: Record<
  PlaceArea,
  { label: string; shortLabel: string; description: string }
> = {
  west: {
    label: "Duke West Campus",
    shortLabel: "West",
    description: "课程、宿舍、图书馆与餐饮",
  },
  east: {
    label: "East Campus + Swift",
    shortLabel: "East",
    description: "一年级宿舍、East–West 校车与 Swift",
  },
  ninth: {
    label: "Ninth Street",
    shortLabel: "9th St",
    description: "步行可达的餐厅、咖啡与夜宵",
  },
  essentials: {
    label: "生活服务",
    shortLabel: "生活",
    description: "超市、银行、食品店与日常采购",
  },
  durham: {
    label: "Durham 游览",
    shortLabel: "Durham",
    description: "市中心、博物馆、公园与演出",
  },
  triangle: {
    label: "Triangle 周边",
    shortLabel: "周边",
    description: "Chapel Hill、Raleigh 与 Cary",
  },
  travel: {
    label: "机场与远行",
    shortLabel: "机场",
    description: "RDU 航站楼与地面交通",
  },
};

export const AREA_ORDER: PlaceArea[] = [
  "west",
  "east",
  "ninth",
  "essentials",
  "durham",
  "triangle",
  "travel",
];

const BASE_PLACES: Place[] = [
  {
    id: "edens-1a",
    name: "Edens Quad 1A",
    shortName: "Edens 1A",
    category: "home",
    categoryLabel: "宿舍 · 默认起点",
    coordinates: [35.99847, -78.93678],
    address: "419 Towerview Drive",
    summary: "你的默认路线起点。点位已按 Duke 官方地址与建筑轮廓交叉核验。",
    facts: [
      "洗衣房：1 楼，24 小时开放",
      "无障碍/全性别卫生间：1 楼 102T、103T",
      "邮件地址：419 Towerview Drive",
      "路线终点落在 1A 建筑边缘，抵达后请以现场入口为准",
    ],
    source: {
      label: "Duke Campus Mail + OSM building",
      url: "https://postoffice.duke.edu/addressing-mail/dormitory-street-addresses/",
      checkedAt: "2026-07-23",
    },
    confidence: "cross-checked",
    markerLabel: "1A",
    links: [
      {
        label: "官方洗衣房信息",
        url: "https://www.dukestores.duke.edu/index.php/laundry/",
      },
      {
        label: "Edens 楼层图",
        url: "https://students.duke.edu/living/housing/upperclass-housing/upperclass-floor-plans/",
      },
    ],
  },
  {
    id: "physics",
    name: "Physics Building",
    shortName: "Physics",
    category: "class",
    categoryLabel: "数学课",
    coordinates: [36.003137, -78.942266],
    room: "235",
    address: "120 Science Drive",
    summary: "MATH 333 与候补 MATH 431 都在 Physics 235，换课不需要改变路线。",
    facts: [
      "MATH 333 · Complex Analysis",
      "MATH 431 · Real Analysis（候补）",
      "点位来自 Physics Building 主大厅官方 ePrint 坐标",
    ],
    source: {
      label: "Duke ePrint · Physics Lobby",
      url: "https://eprint.oit.duke.edu/printers/1081",
      checkedAt: "2026-07-23",
    },
    confidence: "verified",
    markerLabel: "P",
  },
  {
    id: "social-sciences",
    name: "Social Sciences Building",
    shortName: "Social Sciences",
    category: "class",
    categoryLabel: "全球健康课",
    coordinates: [36.001843, -78.937277],
    room: "136",
    address: "419 Chapel Drive",
    summary: "GLHLTH 101 的上课地点。点位取自楼内官方设备坐标。",
    facts: [
      "GLHLTH 101",
      "周一、周三 10:05–11:20",
      "教室：Social Sciences 136",
    ],
    source: {
      label: "Duke ePrint · SocSci 211",
      url: "https://eprint.oit.duke.edu/printers/73",
      checkedAt: "2026-07-23",
    },
    confidence: "verified",
    markerLabel: "S",
  },
  {
    id: "french-science",
    name: "French Family Science Center",
    shortName: "French Science",
    category: "class",
    categoryLabel: "会计课",
    coordinates: [36.002862, -78.943388],
    room: "2231",
    summary: "Financial Accounting 174 的计划地点。课程 section 与教室仍应以 DukeHub 为最终依据。",
    facts: [
      "Financial Accounting 174",
      "周二、周四 8:30–9:45",
      "教室：French Science 2231",
      "楼内全性别卫生间分布在低层及 1–3 楼",
    ],
    source: {
      label: "Duke ePrint · FFSC Lower Level",
      url: "https://eprint.oit.duke.edu/printers/1066",
      checkedAt: "2026-07-23",
    },
    confidence: "verified",
    markerLabel: "F",
  },
  {
    id: "languages",
    name: "Languages Building",
    shortName: "Languages",
    category: "class",
    categoryLabel: "韩语课",
    coordinates: [36.002133, -78.938161],
    summary: "KOREAN 101 的备选地点。具体 section、时间和教室需在 DukeHub 最终确认。",
    facts: [
      "KOREAN 101",
      "备选：周一、周三、周五 11:45–13:00",
      "地点坐标来自 Romance Languages 楼内官方设备",
    ],
    source: {
      label: "Duke ePrint · Romance Languages",
      url: "https://eprint.oit.duke.edu/printers/158",
      checkedAt: "2026-07-23",
    },
    confidence: "review",
    markerLabel: "L",
  },
  {
    id: "bryan-center",
    name: "Bryan Center",
    shortName: "Bryan Center",
    category: "food",
    categoryLabel: "餐饮与生活",
    coordinates: [36.001139, -78.941588],
    address: "125 Science Drive",
    summary: "2026 年官方餐饮名单已更新；旧版中的 Panda、Twinnie's 与 Starbucks 不再作为当前 Bryan 清单。",
    facts: [
      "Beyu Blue Coffee · Bryan 外、Duke Store 入口附近",
      "McDonald's · 2 楼",
      "Gothic Grill · 2 楼",
      "It's Thyme · Plaza Level",
      "ePrint：Lower Level；ATM/Vending Room 另有打印机",
    ],
    source: {
      label: "Duke ePrint · Bryan Lower Level",
      url: "https://eprint.oit.duke.edu/printers/142",
      checkedAt: "2026-07-23",
    },
    confidence: "verified",
    markerLabel: "B",
    links: [
      {
        label: "查看官方餐饮与菜单",
        url: "https://students.duke.edu/living/dining/dining-locations/",
      },
    ],
  },
  {
    id: "brodhead",
    name: "Brodhead Center",
    shortName: "Brodhead",
    category: "food",
    categoryLabel: "主餐饮中心",
    coordinates: [36.000728, -78.939136],
    summary: "原 West Union。适合课间吃饭，餐厅选择比 Bryan Center 更集中。",
    facts: [
      "主要餐饮中心，多层分布",
      "Ground Floor 058T 有全性别卫生间",
      "2 楼 Vending Room 有 ePrint",
      "营业时间与菜单以 Duke Dining 当天信息为准",
    ],
    source: {
      label: "Duke ePrint · Brodhead Center",
      url: "https://eprint.oit.duke.edu/printers/899",
      checkedAt: "2026-07-23",
    },
    confidence: "verified",
    markerLabel: "D",
    links: [
      {
        label: "查看官方餐饮与菜单",
        url: "https://students.duke.edu/living/dining/dining-locations/",
      },
    ],
  },
  {
    id: "perkins",
    name: "Perkins Library",
    shortName: "Perkins",
    category: "study",
    categoryLabel: "长时间自习",
    coordinates: [36.003264, -78.938178],
    summary: "适合数学作业和长时间学习。与 Bostock 相连。",
    facts: [
      "1 楼 Lobby / Breezeway 有多台 ePrint",
      "地下层 The Link 有 OIT 服务台",
      "开放时间会随学期变化",
    ],
    source: {
      label: "Duke ePrint · Perkins Lobby",
      url: "https://eprint.oit.duke.edu/printers/186",
      checkedAt: "2026-07-23",
    },
    confidence: "verified",
    markerLabel: "K",
    links: [
      {
        label: "Duke Libraries",
        url: "https://library.duke.edu/",
      },
    ],
  },
  {
    id: "bostock",
    name: "Bostock Library",
    shortName: "Bostock",
    category: "study",
    categoryLabel: "安静自习",
    coordinates: [36.002903, -78.938339],
    summary: "靠近 Perkins，适合课间停留和安静学习。",
    facts: [
      "The Edge 有黑白和彩色 ePrint",
      "与 Perkins 直接相连",
      "点位来自 The Edge 官方设备坐标",
    ],
    source: {
      label: "Duke ePrint · Bostock Edge",
      url: "https://eprint.oit.duke.edu/printers/172",
      checkedAt: "2026-07-23",
    },
    confidence: "verified",
    markerLabel: "O",
  },
  {
    id: "duke-chapel",
    name: "Duke Chapel",
    shortName: "Chapel",
    category: "landmark",
    categoryLabel: "方向参照",
    coordinates: [36.0018682, -78.9402861],
    summary: "West Campus 最清晰的方向参照点。",
    facts: [
      "从 Chapel 向西南可到 Bryan Center",
      "向东南可到 Brodhead 与 Social Sciences",
      "建筑点位使用 OpenStreetMap 并对照 Duke 官方校园图",
    ],
    source: {
      label: "Duke Campus Map + OpenStreetMap",
      url: "https://maps.duke.edu/",
      checkedAt: "2026-07-23",
    },
    confidence: "cross-checked",
    markerLabel: "C",
  },
  {
    id: "few-quad",
    name: "Few Quad",
    shortName: "Few Quad",
    category: "home",
    categoryLabel: "West 宿舍",
    area: "west",
    coordinates: [36.000083, -78.938523],
    summary: "位于 West Campus 中心，靠近 Chapel、Brodhead 与主教学区。",
    facts: ["约 430 名高年级学生", "设有厨房、自习室、洗衣房和 ePrint"],
    source: {
      label: "Duke Student Affairs · Few Quad",
      url: "https://students.duke.edu/quadex/few-quad/",
      checkedAt: "2026-07-23",
    },
    confidence: "cross-checked",
    markerLabel: "FQ",
    previewEmoji: "🏠",
  },
  {
    id: "keohane-quad",
    name: "Keohane Quad",
    shortName: "Keohane",
    category: "home",
    categoryLabel: "West 宿舍",
    area: "west",
    coordinates: [35.99895, -78.9376],
    summary: "靠近 Edens、Wannamaker 与 Towerview Drive 的 West Campus 宿舍群。",
    facts: ["包含 Keohane 4A、4B、4D、4E", "从 Edens 步行可达"],
    source: {
      label: "Duke Housing · Upperclass Floor Plans",
      url: "https://students.duke.edu/living/housing/upperclass-housing/upperclass-floor-plans/",
      checkedAt: "2026-07-23",
    },
    confidence: "cross-checked",
    markerLabel: "KQ",
    previewEmoji: "🏠",
  },
  {
    id: "wannamaker-quad",
    name: "Wannamaker Quad",
    shortName: "Wannamaker",
    category: "home",
    categoryLabel: "West 宿舍",
    area: "west",
    coordinates: [35.99866, -78.93913],
    summary: "West Campus 南侧宿舍群，靠近 Towerview Road 与体育设施方向。",
    facts: ["包含 Wannamaker 1–4", "Duke Dining 校园配送设有附近取餐点"],
    source: {
      label: "Duke Housing · Upperclass Floor Plans",
      url: "https://students.duke.edu/living/housing/upperclass-housing/upperclass-floor-plans/",
      checkedAt: "2026-07-23",
    },
    confidence: "cross-checked",
    markerLabel: "WQ",
    previewEmoji: "🏠",
  },
  {
    id: "east-bus-stop",
    name: "East Campus Statue Shuttle Stop",
    shortName: "East Campus Stop",
    category: "transit",
    categoryLabel: "C1 / CSF 校车站",
    area: "east",
    coordinates: [36.0052024856, -78.9147518322],
    summary: "当前 CSF/C1–Swift 的 East Campus 主站；因施工已临时移至 East Campus Statue。",
    facts: ["临时站位来自当前 Duke GTFS", "用 TransLoc 查看恢复 Quad 站位与临时调整"],
    source: {
      label: "Duke Transit · CSF East–Swift–West",
      url: "https://parking.duke.edu/buses-vans/csf-east-swift-avenue-west/",
      checkedAt: "2026-07-23",
    },
    confidence: "verified",
    markerLabel: "C1",
    previewEmoji: "🚌",
    shuttle: {
      route: "C1 / CSF",
      summary: "East Campus Quad ↔ Swift Avenue ↔ West Campus Chapel",
      liveUrl: "https://duke.transloc.com/",
    },
  },
  {
    id: "east-marketplace",
    name: "East Union Marketplace",
    shortName: "Marketplace",
    category: "food",
    categoryLabel: "East 主餐厅",
    area: "east",
    coordinates: [36.0069, -78.91475],
    summary: "East Campus 的主要学生餐厅，提供早餐、晚餐、周末早午餐与工作日午餐。",
    facts: ["位于 East Union", "营业时间和菜单以 Duke Dining 当天信息为准"],
    source: {
      label: "Duke Dining · Marketplace",
      url: "https://students.duke.edu/living/dining/dining-locations/",
      checkedAt: "2026-07-23",
    },
    confidence: "verified",
    markerLabel: "MP",
    previewEmoji: "🍽️",
    shuttle: {
      route: "C1 / CSF",
      summary: "West Campus Chapel → East Campus Quad，下车后步行",
      liveUrl: "https://duke.transloc.com/",
    },
  },
  {
    id: "lilly-library",
    name: "Lilly Library",
    shortName: "Lilly Library",
    category: "study",
    categoryLabel: "East 自习",
    area: "east",
    coordinates: [36.0076033, -78.9153485],
    summary: "East Campus 图书馆与安静学习点，靠近主草坪和宿舍区。",
    facts: ["开放时间随学期变化", "适合 East Campus 课间学习"],
    source: {
      label: "Duke Libraries · Lilly Library",
      url: "https://library.duke.edu/lilly",
      checkedAt: "2026-07-23",
    },
    confidence: "cross-checked",
    markerLabel: "LL",
    previewEmoji: "📚",
    shuttle: {
      route: "C1 / CSF",
      summary: "West Campus Chapel → East Campus Quad，下车后步行",
      liveUrl: "https://duke.transloc.com/",
    },
  },
  {
    id: "baldwin-auditorium",
    name: "Baldwin Auditorium",
    shortName: "Baldwin",
    category: "landmark",
    categoryLabel: "演出与活动",
    area: "east",
    coordinates: [36.0090551, -78.9146329],
    summary: "East Campus 标志性礼堂，常举办音乐会、演讲和校园活动。",
    facts: ["靠近 East Campus 主草坪北侧", "活动时间以 Duke Arts 为准"],
    source: {
      label: "Duke Arts · Venues",
      url: "https://arts.duke.edu/venues/",
      checkedAt: "2026-07-23",
    },
    confidence: "cross-checked",
    markerLabel: "BA",
    previewEmoji: "🎭",
    shuttle: {
      route: "C1 / CSF",
      summary: "West Campus Chapel → East Campus Quad，下车后步行",
      liveUrl: "https://duke.transloc.com/",
    },
  },
  {
    id: "brodie-recreation",
    name: "Brodie Recreation Center",
    shortName: "Brodie Gym",
    category: "landmark",
    categoryLabel: "健身运动",
    area: "east",
    coordinates: [36.0076447, -78.9170402],
    summary: "East Campus 的主要健身与体育设施。",
    facts: ["开放时间可能随假期和学期调整", "携带 DukeCard"],
    source: {
      label: "Duke Recreation & Physical Education",
      url: "https://recreation.duke.edu/facilities/",
      checkedAt: "2026-07-23",
    },
    confidence: "cross-checked",
    markerLabel: "BR",
    previewEmoji: "🏋️",
    shuttle: {
      route: "C1 / CSF",
      summary: "West Campus Chapel → East Campus Quad，下车后步行",
      liveUrl: "https://duke.transloc.com/",
    },
  },
  {
    id: "alspaugh-hall",
    name: "Alspaugh Residence Hall",
    shortName: "Alspaugh",
    category: "home",
    categoryLabel: "East 宿舍",
    area: "east",
    coordinates: [36.0081507, -78.9152177],
    summary: "East Campus 一年级宿舍，靠近 Baldwin Auditorium 与 Lilly Library。",
    facts: ["约 120 名一年级学生", "East Campus 14 栋一年级宿舍之一"],
    source: {
      label: "Duke Housing · East Campus Houses",
      url: "https://students.duke.edu/living/housing/first-year-housing/east-campus-houses/",
      checkedAt: "2026-07-23",
    },
    confidence: "cross-checked",
    markerLabel: "AL",
    previewEmoji: "🛏️",
    shuttle: {
      route: "C1 / CSF",
      summary: "West Campus Chapel → East Campus Quad，下车后步行",
      liveUrl: "https://duke.transloc.com/",
    },
  },
  {
    id: "blackwell-hall",
    name: "Blackwell Residence Hall",
    shortName: "Blackwell",
    category: "home",
    categoryLabel: "East 宿舍",
    area: "east",
    coordinates: [36.0064482, -78.9164539],
    summary: "East Campus 一年级宿舍，靠近 Brodie Recreation Center。",
    facts: ["设有中央空调", "宿舍信息与开放设施以 HRL 为准"],
    source: {
      label: "Duke Housing · East Campus Houses",
      url: "https://students.duke.edu/living/housing/first-year-housing/east-campus-houses/",
      checkedAt: "2026-07-23",
    },
    confidence: "cross-checked",
    markerLabel: "BL",
    previewEmoji: "🛏️",
    shuttle: {
      route: "C1 / CSF",
      summary: "West Campus Chapel → East Campus Quad，下车后步行",
      liveUrl: "https://duke.transloc.com/",
    },
  },
  {
    id: "southgate-hall",
    name: "Southgate Residence Hall",
    shortName: "Southgate",
    category: "home",
    categoryLabel: "East 宿舍",
    area: "east",
    coordinates: [36.0060314, -78.9179317],
    summary: "East Campus 西南侧的一年级宿舍，靠近 Swift 与 Main Street 方向。",
    facts: ["设有中央空调", "1921 年建成"],
    source: {
      label: "Duke Housing · East Campus Houses",
      url: "https://students.duke.edu/living/housing/first-year-housing/east-campus-houses/",
      checkedAt: "2026-07-23",
    },
    confidence: "cross-checked",
    markerLabel: "SG",
    previewEmoji: "🛏️",
    shuttle: {
      route: "C1 / CSF",
      summary: "West Campus Chapel → East Campus Quad，下车后步行",
      liveUrl: "https://duke.transloc.com/",
    },
  },
  {
    id: "trinity-hall",
    name: "Trinity Residence Hall",
    shortName: "Trinity",
    category: "home",
    categoryLabel: "East 宿舍",
    area: "east",
    coordinates: [36.0065411, -78.9186292],
    summary: "East Campus 西侧一年级宿舍，邻近 Southgate 与 Main Street。",
    facts: ["设有中央空调", "靠近 East Campus 西侧出口"],
    source: {
      label: "Duke Housing · East Campus Houses",
      url: "https://students.duke.edu/living/housing/first-year-housing/east-campus-houses/",
      checkedAt: "2026-07-23",
    },
    confidence: "cross-checked",
    markerLabel: "TR",
    previewEmoji: "🛏️",
    shuttle: {
      route: "C1 / CSF",
      summary: "West Campus Chapel → East Campus Quad，下车后步行",
      liveUrl: "https://duke.transloc.com/",
    },
  },
  {
    id: "swift-300",
    name: "300 Swift Avenue",
    shortName: "300 Swift",
    category: "transit",
    categoryLabel: "SWS / CSF 校车站",
    area: "east",
    coordinates: [36.0027490109, -78.9215145362],
    summary: "Swift Avenue 学生公寓与校车站，连接 East、Swift 和 West Campus。",
    facts: ["CSF 站点 ID 13009", "学期内另有 Swift Avenue Shuttle"],
    source: {
      label: "Duke Transit · CSF East–Swift–West",
      url: "https://parking.duke.edu/buses-vans/csf-east-swift-avenue-west/",
      checkedAt: "2026-07-23",
    },
    confidence: "verified",
    markerLabel: "SW",
    previewEmoji: "🚌",
    shuttle: {
      route: "SWS / CSF",
      summary: "East Campus ↔ 300 Swift ↔ West Campus",
      liveUrl: "https://duke.transloc.com/",
    },
  },
  {
    id: "blue-light-living",
    name: "The Blue Light Living",
    shortName: "Blue Light",
    category: "home",
    categoryLabel: "校外学生公寓",
    area: "east",
    coordinates: [36.005522, -78.9226205],
    address: "1605 Erwin Road",
    summary: "Duke 附近学生公寓，CSF 路线在 East→West 方向停靠。",
    facts: ["CSF 站点 ID 12131", "实时站位与班次请查看 TransLoc"],
    source: {
      label: "Duke Transit · CSF East–Swift–West",
      url: "https://parking.duke.edu/buses-vans/csf-east-swift-avenue-west/",
      checkedAt: "2026-07-23",
    },
    confidence: "cross-checked",
    markerLabel: "BL",
    previewEmoji: "🏢",
    shuttle: {
      route: "CSF",
      summary: "East Campus → Blue Light → Swift → West Campus",
      liveUrl: "https://duke.transloc.com/",
    },
  },
  {
    id: "elmos-diner",
    name: "Elmo's Diner",
    shortName: "Elmo's Diner",
    category: "food",
    categoryLabel: "美式早餐 · Diner",
    area: "ninth",
    coordinates: [36.0104063, -78.9216996],
    address: "776 9th Street",
    summary: "Ninth Street 长期学生热门餐厅，适合早餐、早午餐和经典 diner 菜单。",
    facts: ["高峰时段可能排队", "从 East Campus 步行可达"],
    source: {
      label: "Discover Durham · Ninth Street Guide",
      url: "https://www.discoverdurham.com/district-guides/the-ultimate-guide-to-ninth-street-duke-university/",
      checkedAt: "2026-07-23",
    },
    confidence: "cross-checked",
    markerLabel: "ED",
    previewEmoji: "🍳",
  },
  {
    id: "monuts",
    name: "Monuts",
    shortName: "Monuts",
    category: "food",
    categoryLabel: "早餐 · 甜甜圈",
    area: "ninth",
    coordinates: [36.0139103, -78.9215285],
    address: "1002 9th Street",
    summary: "以自制甜甜圈、早餐和早午餐闻名的 Ninth Street 餐厅。",
    facts: ["通常周二至周六营业", "营业时间可能变化，出发前查看官网"],
    source: {
      label: "Discover Durham · Ninth Street Guide",
      url: "https://www.discoverdurham.com/directory/monuts/",
      checkedAt: "2026-07-23",
    },
    confidence: "cross-checked",
    markerLabel: "MO",
    previewEmoji: "🍩",
  },
  {
    id: "cosmic-cantina",
    name: "Cosmic Cantina",
    shortName: "Cosmic Cantina",
    category: "food",
    categoryLabel: "墨西哥 · 夜宵",
    area: "ninth",
    coordinates: [36.0077961, -78.9218492],
    address: "1920 Perry Street",
    summary: "Ninth Street 附近的学生经典夜宵点，以 burrito 和 quesadilla 为主。",
    facts: ["入口较隐蔽，位于楼上", "以当日营业时间为准"],
    source: {
      label: "Discover Durham · Duke Hotspots",
      url: "https://www.discoverdurham.com/blog/best-hotspots-duke-university/",
      checkedAt: "2026-07-23",
    },
    confidence: "cross-checked",
    markerLabel: "CC",
    previewEmoji: "🌯",
  },
  {
    id: "lime-lemon",
    name: "Lime & Lemon Indian Grill",
    shortName: "Lime & Lemon",
    category: "food",
    categoryLabel: "印度菜",
    area: "ninth",
    coordinates: [36.0113, -78.92162],
    address: "811 9th Street",
    summary: "提供多地区印度菜，适合聚餐和外卖。",
    facts: ["靠近 Ninth Street 中段", "菜单和营业时间以餐厅官网为准"],
    source: {
      label: "Discover Durham · Ninth Street Guide",
      url: "https://www.discoverdurham.com/district-guides/the-ultimate-guide-to-ninth-street-duke-university/",
      checkedAt: "2026-07-23",
    },
    confidence: "cross-checked",
    markerLabel: "L&L",
    previewEmoji: "🍛",
  },
  {
    id: "dains-place",
    name: "Dain's Place",
    shortName: "Dain's Place",
    category: "food",
    categoryLabel: "汉堡 · Bar",
    area: "ninth",
    coordinates: [36.0095674, -78.9217353],
    address: "754 9th Street",
    summary: "Ninth Street 社区酒吧与汉堡店，适合轻松聚餐。",
    facts: ["晚间氛围为主", "酒精饮品须符合年龄规定"],
    source: {
      label: "Discover Durham · Ninth Street Guide",
      url: "https://www.discoverdurham.com/district-guides/the-ultimate-guide-to-ninth-street-duke-university/",
      checkedAt: "2026-07-23",
    },
    confidence: "cross-checked",
    markerLabel: "DP",
    previewEmoji: "🍔",
  },
  {
    id: "banhs-cuisine",
    name: "Banh's Cuisine",
    shortName: "Banh's Cuisine",
    category: "food",
    categoryLabel: "越南 · 中餐",
    area: "ninth",
    coordinates: [36.0094817, -78.9218716],
    address: "752 9th Street",
    summary: "朴实的越南与中式餐馆，部分特色菜仅在特定日期供应。",
    facts: ["部分时段可能只收现金", "周三、周六常有越南特色菜单"],
    source: {
      label: "Discover Durham · Ninth Street Guide",
      url: "https://www.discoverdurham.com/district-guides/the-ultimate-guide-to-ninth-street-duke-university/",
      checkedAt: "2026-07-23",
    },
    confidence: "cross-checked",
    markerLabel: "BH",
    previewEmoji: "🍜",
  },
  {
    id: "vin-rouge",
    name: "Vin Rouge",
    shortName: "Vin Rouge",
    category: "food",
    categoryLabel: "法餐",
    area: "ninth",
    coordinates: [36.0106219, -78.9223235],
    address: "2010 Hillsborough Road",
    summary: "Ninth Street 附近的法式餐厅，更适合正式晚餐或庆祝。",
    facts: ["建议提前预约", "价格通常高于学生日常餐厅"],
    source: {
      label: "Discover Durham · Ninth Street Guide",
      url: "https://www.discoverdurham.com/directory/vin-rouge/",
      checkedAt: "2026-07-23",
    },
    confidence: "cross-checked",
    markerLabel: "VR",
    previewEmoji: "🇫🇷",
  },
  {
    id: "juju-durham",
    name: "Juju Durham",
    shortName: "Juju",
    category: "food",
    categoryLabel: "亚洲融合 · Tapas",
    area: "ninth",
    coordinates: [36.0096915, -78.9223473],
    address: "737 9th Street",
    summary: "亚洲融合小盘菜与鸡尾酒餐厅，设有露台。",
    facts: ["适合多人分享", "晚餐时段建议预约"],
    source: {
      label: "Discover Durham · Ninth Street Guide",
      url: "https://www.discoverdurham.com/district-guides/the-ultimate-guide-to-ninth-street-duke-university/",
      checkedAt: "2026-07-23",
    },
    confidence: "cross-checked",
    markerLabel: "JU",
    previewEmoji: "🥢",
  },
  {
    id: "cloche-coffee",
    name: "Cloche Coffee",
    shortName: "Cloche Coffee",
    category: "food",
    categoryLabel: "咖啡 · 学习",
    area: "ninth",
    coordinates: [36.0077, -78.92295],
    address: "721 Broad Street",
    summary: "East Campus 对面的植物系咖啡店，适合短时间学习和聊天。",
    facts: ["座位数量有限", "从 East Campus 步行方便"],
    source: {
      label: "Discover Durham · Ninth Street Guide",
      url: "https://www.discoverdurham.com/district-guides/the-ultimate-guide-to-ninth-street-duke-university/",
      checkedAt: "2026-07-23",
    },
    confidence: "cross-checked",
    markerLabel: "CL",
    previewEmoji: "☕",
  },
  {
    id: "cocoa-cinnamon",
    name: "Cocoa Cinnamon · Old West Durham",
    shortName: "Cocoa Cinnamon",
    category: "food",
    categoryLabel: "咖啡 · 巧克力",
    area: "ninth",
    coordinates: [36.0115807, -78.9301586],
    address: "2627 Hillsborough Road",
    summary: "Old West Durham 的本地咖啡店，适合作为 Ninth Street 以西的休息点。",
    facts: ["离 Ninth Street 核心区稍远", "适合骑行或短途驾车"],
    source: {
      label: "Discover Durham · Ninth Street Guide",
      url: "https://www.discoverdurham.com/district-guides/the-ultimate-guide-to-ninth-street-duke-university/",
      checkedAt: "2026-07-23",
    },
    confidence: "cross-checked",
    markerLabel: "CO",
    previewEmoji: "☕",
  },
  {
    id: "whole-foods-durham",
    name: "Whole Foods Market · Durham",
    shortName: "Whole Foods",
    category: "shopping",
    categoryLabel: "生鲜超市",
    area: "essentials",
    coordinates: [36.0070992, -78.9205563],
    address: "621 Broad Street",
    summary: "离 East Campus 和 Ninth Street 最近的大型生鲜超市之一。",
    facts: ["适合日常生鲜和即食食品", "停车区高峰时段可能拥挤"],
    source: {
      label: "Whole Foods · Durham Store",
      url: "https://www.wholefoodsmarket.com/stores/durham",
      checkedAt: "2026-07-23",
    },
    confidence: "verified",
    markerLabel: "WF",
    previewEmoji: "🥬",
  },
  {
    id: "harris-teeter-ninth",
    name: "Harris Teeter · Ninth Street",
    shortName: "Harris Teeter",
    category: "shopping",
    categoryLabel: "综合超市 · 药房",
    area: "essentials",
    coordinates: [36.009799, -78.9241832],
    address: "2107 Hillsborough Road",
    summary: "Ninth Street 附近的综合超市，店内设药房。",
    facts: ["适合大部分日常采购", "可步行、骑行或驾车前往"],
    source: {
      label: "Harris Teeter · Durham Store",
      url: "https://www.harristeeter.com/stores/pharmacy/nc/durham/097/00394",
      checkedAt: "2026-07-23",
    },
    confidence: "verified",
    markerLabel: "HT",
    previewEmoji: "🛒",
  },
  {
    id: "food-lion-west-main",
    name: "Food Lion · West Main",
    shortName: "Food Lion",
    category: "shopping",
    categoryLabel: "平价超市",
    area: "essentials",
    coordinates: [36.0142132, -78.9340045],
    address: "2930 West Main Street",
    summary: "Old West Durham 的日常超市，适合预算型采购。",
    facts: ["离 West Campus 不远", "建议骑行或驾车"],
    source: {
      label: "North Carolina Authorized Retailer List",
      url: "https://www.ncdhhs.gov/north-carolina-authorized-wic-vendors/open",
      checkedAt: "2026-07-23",
    },
    confidence: "cross-checked",
    markerLabel: "FL",
    previewEmoji: "🛒",
  },
  {
    id: "durham-coop",
    name: "Durham Co-op Market",
    shortName: "Durham Co-op",
    category: "shopping",
    categoryLabel: "本地合作社超市",
    area: "essentials",
    coordinates: [35.9965133, -78.9167043],
    address: "1111 West Chapel Hill Street",
    summary: "社区型食品合作社，提供本地商品、熟食和日常杂货。",
    facts: ["靠近 Burch Avenue", "适合骑行或驾车"],
    source: {
      label: "Durham Co-op Market",
      url: "https://durham.coop/",
      checkedAt: "2026-07-23",
    },
    confidence: "cross-checked",
    markerLabel: "DC",
    previewEmoji: "🥕",
  },
  {
    id: "li-mings",
    name: "Li Ming's Global Mart",
    shortName: "Li Ming's",
    category: "shopping",
    categoryLabel: "亚洲食品超市",
    area: "essentials",
    coordinates: [35.9662353, -78.9629676],
    address: "3400 Westgate Drive",
    summary: "大型亚洲食品超市，适合买亚洲调料、蔬菜、冷冻食品和零食。",
    facts: ["离校园较远，推荐驾车", "可与 South Square 采购行程合并"],
    source: {
      label: "OpenStreetMap + Store Listing",
      url: "https://www.openstreetmap.org/?mlat=35.9662353&mlon=-78.9629676#map=18/35.9662353/-78.9629676",
      checkedAt: "2026-07-23",
    },
    confidence: "cross-checked",
    markerLabel: "LM",
    previewEmoji: "🥟",
  },
  {
    id: "costco-durham",
    name: "Costco Wholesale · Durham",
    shortName: "Costco",
    category: "shopping",
    categoryLabel: "仓储超市",
    area: "essentials",
    coordinates: [36.0290976, -78.9138789],
    address: "1510 North Pointe Drive",
    summary: "适合多人合购和大包装采购，需要会员。",
    facts: ["建议驾车前往", "高峰时段停车场可能拥挤"],
    source: {
      label: "Costco Warehouse Locator",
      url: "https://www.costco.com/warehouse-locations/durham-nc-249.html",
      checkedAt: "2026-07-23",
    },
    confidence: "cross-checked",
    markerLabel: "CT",
    previewEmoji: "📦",
  },
  {
    id: "target-south-square",
    name: "Target · South Square",
    shortName: "Target",
    category: "shopping",
    categoryLabel: "综合零售",
    area: "essentials",
    coordinates: [35.965602, -78.960766],
    address: "4037 Durham-Chapel Hill Boulevard",
    summary: "适合买宿舍用品、日化、简单食品和生活杂货。",
    facts: ["与 Li Ming's 距离较近", "推荐驾车"],
    source: {
      label: "Target Store Locator",
      url: "https://www.target.com/store-locator/find-stores/27707",
      checkedAt: "2026-07-23",
    },
    confidence: "cross-checked",
    markerLabel: "TG",
    previewEmoji: "🎯",
  },
  {
    id: "walmart-new-hope",
    name: "Walmart · New Hope Commons",
    shortName: "Walmart",
    category: "shopping",
    categoryLabel: "综合超市",
    area: "essentials",
    coordinates: [35.9550347, -78.9990623],
    address: "5450 New Hope Commons Drive",
    summary: "大型综合超市，适合一次性采购宿舍和生活用品。",
    facts: ["离校园较远，推荐驾车", "可与 New Hope Commons 其他商店合并"],
    source: {
      label: "Walmart Store Finder",
      url: "https://www.walmart.com/store/3182-durham-nc",
      checkedAt: "2026-07-23",
    },
    confidence: "cross-checked",
    markerLabel: "WM",
    previewEmoji: "🛒",
  },
  {
    id: "duke-credit-union",
    name: "Duke University Credit Union",
    shortName: "Duke Credit Union",
    category: "service",
    categoryLabel: "银行 · 信用合作社",
    area: "essentials",
    coordinates: [36.0075572, -78.9262548],
    address: "2200 West Main Street, Suite L100",
    summary: "面向符合资格的 Duke 社区成员提供银行与信用合作社服务。",
    facts: ["到访前确认开户资格与营业时间", "官方电话：919-684-6704"],
    source: {
      label: "Duke University Credit Union",
      url: "https://www.dukefcu.org/",
      checkedAt: "2026-07-23",
    },
    confidence: "verified",
    markerLabel: "CU",
    previewEmoji: "🏦",
  },
  {
    id: "rdu-terminal-2",
    name: "RDU Airport · Terminal 2",
    shortName: "RDU Terminal 2",
    category: "transit",
    categoryLabel: "机场 · 主要航站楼",
    area: "travel",
    coordinates: [35.8782578, -78.7924525],
    address: "2400 John Brantley Boulevard",
    summary: "RDU 的主要航站楼，多数航空公司从这里出发。",
    facts: ["网约车、出租车与公共交通上车点按现场指示", "预留安检和道路拥堵时间"],
    source: {
      label: "RDU · Ground Transportation",
      url: "https://www.rdu.com/ground-transportation/",
      checkedAt: "2026-07-23",
    },
    confidence: "verified",
    markerLabel: "T2",
    previewEmoji: "✈️",
    links: [
      {
        label: "RDU 公交与区域交通",
        url: "https://www.rdu.com/ground-transportation/bus-and-rail-service/",
      },
    ],
  },
  {
    id: "rdu-terminal-1",
    name: "RDU Airport · Terminal 1",
    shortName: "RDU Terminal 1",
    category: "transit",
    categoryLabel: "机场航站楼",
    area: "travel",
    coordinates: [35.8785, -78.7872],
    summary: "RDU Terminal 1；出发前按航空公司确认航站楼。",
    facts: ["GoTriangle 服务的停靠区与 Terminal 2 不同", "接送时按现场 Zone 标识"],
    source: {
      label: "RDU · Bus and Rail Service",
      url: "https://www.rdu.com/ground-transportation/bus-and-rail-service/",
      checkedAt: "2026-07-23",
    },
    confidence: "verified",
    markerLabel: "T1",
    previewEmoji: "🛫",
  },
  {
    id: "duke-gardens",
    name: "Sarah P. Duke Gardens",
    shortName: "Duke Gardens",
    category: "attraction",
    categoryLabel: "花园 · 散步",
    area: "durham",
    coordinates: [36.0024247, -78.9328121],
    summary: "55 英亩的校园花园，适合散步、拍照和季节性游览。",
    facts: ["部分区域或停车安排会临时调整", "从 West Campus 可步行"],
    source: {
      label: "Discover Durham · Things to Do",
      url: "https://www.discoverdurham.com/things-to-do/",
      checkedAt: "2026-07-23",
    },
    confidence: "cross-checked",
    markerLabel: "DG",
    previewEmoji: "🌸",
  },
  {
    id: "nasher-museum",
    name: "Nasher Museum of Art",
    shortName: "Nasher Museum",
    category: "attraction",
    categoryLabel: "艺术博物馆",
    area: "durham",
    coordinates: [35.9990522, -78.9290629],
    address: "2001 Campus Drive",
    summary: "Duke 校内艺术博物馆，适合展览、活动和周末参观。",
    facts: ["开放时间与特展以官网为准", "从 West Campus 可步行或骑行"],
    source: {
      label: "Nasher Museum of Art",
      url: "https://nasher.duke.edu/",
      checkedAt: "2026-07-23",
    },
    confidence: "verified",
    markerLabel: "NM",
    previewEmoji: "🖼️",
  },
  {
    id: "american-tobacco",
    name: "American Tobacco Campus",
    shortName: "American Tobacco",
    category: "attraction",
    categoryLabel: "街区 · 餐饮",
    area: "durham",
    coordinates: [35.9943285, -78.904297],
    summary: "改造后的历史工业园区，集合餐厅、活动、步道和 Durham 地标。",
    facts: ["紧邻 DBAP 与 DPAC", "适合和 Downtown Durham 行程合并"],
    source: {
      label: "Discover Durham · Things to Do",
      url: "https://www.discoverdurham.com/things-to-do/",
      checkedAt: "2026-07-23",
    },
    confidence: "cross-checked",
    markerLabel: "AT",
    previewEmoji: "🏙️",
  },
  {
    id: "durham-bulls",
    name: "Durham Bulls Athletic Park",
    shortName: "Durham Bulls",
    category: "attraction",
    categoryLabel: "棒球 · 活动",
    area: "durham",
    coordinates: [35.9915839, -78.9039173],
    address: "409 Blackwell Street",
    summary: "Durham Bulls 主场，比赛日适合与 American Tobacco Campus 一起游览。",
    facts: ["赛程与门票以官方信息为准", "比赛日周边停车和交通较拥挤"],
    source: {
      label: "Durham Bulls",
      url: "https://www.milb.com/durham",
      checkedAt: "2026-07-23",
    },
    confidence: "cross-checked",
    markerLabel: "DB",
    previewEmoji: "⚾",
  },
  {
    id: "life-science-museum",
    name: "Museum of Life and Science",
    shortName: "Life + Science",
    category: "attraction",
    categoryLabel: "科学博物馆",
    area: "durham",
    coordinates: [36.031267, -78.8965307],
    summary: "互动科学馆与大型户外园区，适合半天游览。",
    facts: ["离校园较远，推荐驾车", "门票与开放时间以官网为准"],
    source: {
      label: "Discover Durham · Things to Do",
      url: "https://www.discoverdurham.com/things-to-do/",
      checkedAt: "2026-07-23",
    },
    confidence: "cross-checked",
    markerLabel: "LS",
    previewEmoji: "🦋",
  },
  {
    id: "eno-river",
    name: "Eno River State Park",
    shortName: "Eno River",
    category: "attraction",
    categoryLabel: "州立公园 · 徒步",
    area: "durham",
    coordinates: [36.0749299, -79.0172182],
    summary: "Durham 周边经典徒步和河流自然景区。",
    facts: ["不同入口对应不同步道", "出发前查看天气、停车和闭园信息"],
    source: {
      label: "NC State Parks · Eno River",
      url: "https://www.ncparks.gov/state-parks/eno-river-state-park",
      checkedAt: "2026-07-23",
    },
    confidence: "cross-checked",
    markerLabel: "ER",
    previewEmoji: "🥾",
  },
  {
    id: "duke-lemur-center",
    name: "Duke Lemur Center",
    shortName: "Lemur Center",
    category: "attraction",
    categoryLabel: "动物与科研参观",
    area: "durham",
    coordinates: [35.9941971, -78.9623365],
    summary: "Duke 的狐猴研究与保护中心；参观通常需要提前预约。",
    facts: ["不可将其当作随到随看的普通动物园", "查看官网预约与参观要求"],
    source: {
      label: "Duke Lemur Center",
      url: "https://lemur.duke.edu/visit/",
      checkedAt: "2026-07-23",
    },
    confidence: "verified",
    markerLabel: "LC",
    previewEmoji: "🐒",
  },
  {
    id: "dpac",
    name: "Durham Performing Arts Center",
    shortName: "DPAC",
    category: "attraction",
    categoryLabel: "演出 · 剧院",
    area: "durham",
    coordinates: [35.9932676, -78.9022327],
    address: "123 Vivian Street",
    summary: "Durham 主要演出场馆，音乐剧、喜剧和巡演节目较多。",
    facts: ["紧邻 American Tobacco Campus", "按演出时间规划返程与停车"],
    source: {
      label: "DPAC Official",
      url: "https://www.dpacnc.com/",
      checkedAt: "2026-07-23",
    },
    confidence: "verified",
    markerLabel: "DP",
    previewEmoji: "🎟️",
  },
  {
    id: "southpoint",
    name: "The Streets at Southpoint",
    shortName: "Southpoint",
    category: "shopping",
    categoryLabel: "商场 · 餐饮",
    area: "durham",
    coordinates: [35.90419, -78.9437055],
    address: "6910 Fayetteville Road",
    summary: "Durham 南部大型购物中心，适合买衣物、用餐和集中购物。",
    facts: ["离校园较远，推荐驾车", "周末和节日前后可能拥挤"],
    source: {
      label: "Discover Durham · Things to Do",
      url: "https://www.discoverdurham.com/things-to-do/",
      checkedAt: "2026-07-23",
    },
    confidence: "cross-checked",
    markerLabel: "SP",
    previewEmoji: "🛍️",
  },
  {
    id: "downtown-durham",
    name: "Downtown Durham · CCB Plaza",
    shortName: "Downtown Durham",
    category: "attraction",
    categoryLabel: "市中心 · 逛街",
    area: "durham",
    coordinates: [35.99645, -78.9012],
    summary: "适合作为 Downtown Durham 步行探索的中心点，周边有餐厅、咖啡、商店和活动。",
    facts: ["可与 American Tobacco、DPAC、DBAP 组合", "夜间注意返程交通"],
    source: {
      label: "Discover Durham · Things to Do",
      url: "https://www.discoverdurham.com/things-to-do/",
      checkedAt: "2026-07-23",
    },
    confidence: "cross-checked",
    markerLabel: "DT",
    previewEmoji: "🐂",
  },
  {
    id: "unc-old-well",
    name: "UNC Old Well",
    shortName: "UNC Old Well",
    category: "attraction",
    categoryLabel: "Chapel Hill 地标",
    area: "triangle",
    coordinates: [35.91296, -79.05122],
    summary: "UNC Chapel Hill 的代表性校园地标，可与 Franklin Street 一起游览。",
    facts: ["校园内步行游览", "驾车前确认访客停车"],
    source: {
      label: "UNC Chapel Hill · The Old Well",
      url: "https://www.unc.edu/discover/the-old-well/",
      checkedAt: "2026-07-23",
    },
    confidence: "cross-checked",
    markerLabel: "UNC",
    previewEmoji: "🏛️",
  },
  {
    id: "franklin-street",
    name: "Franklin Street",
    shortName: "Franklin Street",
    category: "attraction",
    categoryLabel: "Chapel Hill 餐饮街区",
    area: "triangle",
    coordinates: [35.9137, -79.0555],
    summary: "UNC 校园旁的主商业街，餐厅、咖啡、书店和夜生活集中。",
    facts: ["适合与 UNC 校园组合", "周末和比赛日停车紧张"],
    source: {
      label: "Visit Chapel Hill",
      url: "https://www.visitchapelhill.org/",
      checkedAt: "2026-07-23",
    },
    confidence: "cross-checked",
    markerLabel: "FS",
    previewEmoji: "🍴",
  },
  {
    id: "nc-botanical-garden",
    name: "North Carolina Botanical Garden",
    shortName: "NC Botanical Garden",
    category: "attraction",
    categoryLabel: "植物园 · 自然",
    area: "triangle",
    coordinates: [35.8973342, -79.0311056],
    summary: "UNC 管理的本土植物园与自然区域。",
    facts: ["适合安静散步", "开放时间与特定步道情况以官网为准"],
    source: {
      label: "North Carolina Botanical Garden",
      url: "https://ncbg.unc.edu/",
      checkedAt: "2026-07-23",
    },
    confidence: "cross-checked",
    markerLabel: "BG",
    previewEmoji: "🌿",
  },
  {
    id: "ncma",
    name: "North Carolina Museum of Art",
    shortName: "NC Museum of Art",
    category: "attraction",
    categoryLabel: "艺术馆 · 户外公园",
    area: "triangle",
    coordinates: [35.8105029, -78.7021777],
    address: "2110 Blue Ridge Road, Raleigh",
    summary: "Raleigh 主要艺术博物馆，并设有大型户外艺术公园和步道。",
    facts: ["适合半天游览", "常设展与户外区域信息以官网为准"],
    source: {
      label: "Visit Raleigh · Museum Guide",
      url: "https://www.visitraleigh.com/things-to-do/museums/museum-guide/",
      checkedAt: "2026-07-23",
    },
    confidence: "cross-checked",
    markerLabel: "MA",
    previewEmoji: "🎨",
  },
  {
    id: "natural-sciences",
    name: "North Carolina Museum of Natural Sciences",
    shortName: "Natural Sciences",
    category: "attraction",
    categoryLabel: "自然科学博物馆",
    area: "triangle",
    coordinates: [35.7821583, -78.6395026],
    address: "11 West Jones Street, Raleigh",
    summary: "Raleigh 市中心大型自然科学博物馆，适合与 State Capitol 一起游览。",
    facts: ["主要常设展通常免费", "特殊展览可能另行购票"],
    source: {
      label: "Visit Raleigh · Museum Guide",
      url: "https://www.visitraleigh.com/things-to-do/museums/museum-guide/",
      checkedAt: "2026-07-23",
    },
    confidence: "cross-checked",
    markerLabel: "NS",
    previewEmoji: "🦖",
  },
  {
    id: "dix-park",
    name: "Dorothea Dix Park",
    shortName: "Dix Park",
    category: "attraction",
    categoryLabel: "公园 · 城市景观",
    area: "triangle",
    coordinates: [35.7700706, -78.6568071],
    summary: "Raleigh 大型城市公园，适合散步、活动和看城市天际线。",
    facts: ["大型活动期间交通安排会变化", "夏季注意高温和遮阴"],
    source: {
      label: "Visit Raleigh · Things to Do",
      url: "https://www.visitraleigh.com/things-to-do/",
      checkedAt: "2026-07-23",
    },
    confidence: "cross-checked",
    markerLabel: "DX",
    previewEmoji: "🌳",
  },
  {
    id: "pullen-park",
    name: "Pullen Park",
    shortName: "Pullen Park",
    category: "attraction",
    categoryLabel: "公园 · 游乐设施",
    area: "triangle",
    coordinates: [35.7821253, -78.663551],
    summary: "靠近 NC State 的历史公园，设旋转木马、小火车和湖边设施。",
    facts: ["适合轻松半日行程", "部分设施需要购票"],
    source: {
      label: "Visit Raleigh · Family Fun",
      url: "https://www.visitraleigh.com/things-to-do/family-fun/",
      checkedAt: "2026-07-23",
    },
    confidence: "cross-checked",
    markerLabel: "PP",
    previewEmoji: "🎠",
  },
  {
    id: "nc-state-capitol",
    name: "North Carolina State Capitol",
    shortName: "NC State Capitol",
    category: "attraction",
    categoryLabel: "历史 · 建筑",
    area: "triangle",
    coordinates: [35.7803975, -78.6390995],
    address: "1 East Edenton Street, Raleigh",
    summary: "Raleigh 市中心历史地标，靠近自然科学博物馆与其他州立机构。",
    facts: ["适合市中心步行线路", "参观开放信息以官网为准"],
    source: {
      label: "Visit Raleigh · Raleigh Guide",
      url: "https://www.visitraleigh.com/plan-a-trip/cities-and-towns/raleigh/",
      checkedAt: "2026-07-23",
    },
    confidence: "cross-checked",
    markerLabel: "SC",
    previewEmoji: "🏛️",
  },
  {
    id: "umstead-park",
    name: "William B. Umstead State Park",
    shortName: "Umstead Park",
    category: "attraction",
    categoryLabel: "州立公园 · 徒步",
    area: "triangle",
    coordinates: [35.8571605, -78.7544348],
    summary: "RDU 附近的大型州立公园，拥有多条森林徒步路线。",
    facts: ["不同入口距离较远", "出发前检查步道、天气和闭园信息"],
    source: {
      label: "NC State Parks · Umstead",
      url: "https://www.ncparks.gov/state-parks/william-b-umstead-state-park",
      checkedAt: "2026-07-23",
    },
    confidence: "cross-checked",
    markerLabel: "UP",
    previewEmoji: "🌲",
  },
  {
    id: "downtown-cary-park",
    name: "Downtown Cary Park",
    shortName: "Downtown Cary Park",
    category: "attraction",
    categoryLabel: "公园 · 餐饮街区",
    area: "triangle",
    coordinates: [35.7838447, -78.77988],
    address: "319 South Academy Street, Cary",
    summary: "Downtown Cary 的大型公共公园，周边有餐厅、活动和步行街区。",
    facts: ["可与 Cary 市中心餐饮组合", "活动日查看停车与道路安排"],
    source: {
      label: "Downtown Cary Park",
      url: "https://downtowncarypark.com/",
      checkedAt: "2026-07-23",
    },
    confidence: "cross-checked",
    markerLabel: "CP",
    previewEmoji: "⛲",
  },
  {
    id: "chase-ninth-street",
    name: "Chase Bank · Durham 9th Street",
    shortName: "Chase Bank",
    category: "service",
    categoryLabel: "银行 · ATM",
    area: "ninth",
    coordinates: [36.008513, -78.92223],
    address: "725 9th Street, Durham",
    summary: "Ninth Street 上的 Chase 分行，可办理日常银行业务并使用 ATM。",
    facts: ["分行与 ATM 服务时间可能不同", "办理业务前建议查看官方营业状态"],
    source: {
      label: "Chase · Durham 9th St",
      url: "https://locator.chase.com/nc/durham/725-9th-st",
      checkedAt: "2026-07-23",
    },
    confidence: "verified",
    markerLabel: "$",
    previewEmoji: "🏦",
  },
  {
    id: "regulator-bookshop",
    name: "The Regulator Bookshop",
    shortName: "Regulator Books",
    category: "shopping",
    categoryLabel: "独立书店",
    area: "ninth",
    coordinates: [36.0085447, -78.9218424],
    address: "720 9th Street, Durham",
    summary: "Ninth Street 的独立书店，适合逛书、买明信片和参加作者活动。",
    facts: ["Triangle 历史较久的独立书店", "活动与营业时间以店铺官网为准"],
    source: {
      label: "The Regulator Bookshop",
      url: "https://www.regulatorbookshop.com/about-us",
      checkedAt: "2026-07-23",
    },
    confidence: "verified",
    markerLabel: "BK",
    previewEmoji: "📚",
  },
  {
    id: "hometown-apparel",
    name: "Hometown Apparel",
    shortName: "Hometown Apparel",
    category: "shopping",
    categoryLabel: "Durham 纪念品 · 服饰",
    area: "ninth",
    coordinates: [36.0090401, -78.9219945],
    address: "738 9th Street, Durham",
    summary: "购买 Bull City 与 Durham 主题衣服、帽子、贴纸和小礼物的本地商店。",
    facts: ["适合买 Durham 纪念品", "由 Discover Durham 当前目录核验"],
    source: {
      label: "Discover Durham · Hometown Apparel",
      url: "https://www.discoverdurham.com/directory/hometown-apparel/",
      checkedAt: "2026-07-23",
    },
    confidence: "verified",
    markerLabel: "HT",
    previewEmoji: "👕",
  },
  {
    id: "durham-cycles",
    name: "Durham Cycles",
    shortName: "Durham Cycles",
    category: "service",
    categoryLabel: "自行车店 · 维修",
    area: "ninth",
    coordinates: [36.009631, -78.9218154],
    address: "756 9th Street, Durham",
    summary: "Ninth Street 的自行车销售与维修店，适合处理轮胎、车链和日常维护。",
    facts: ["可提供自行车与配件建议", "维修等待时间会随旺季变化"],
    source: {
      label: "Discover Durham · Durham Cycles",
      url: "https://www.discoverdurham.com/directory/durham-cycles/",
      checkedAt: "2026-07-23",
    },
    confidence: "verified",
    markerLabel: "DC",
    previewEmoji: "🚲",
  },
  {
    id: "barnes-supply",
    name: "Barnes Supply Co.",
    shortName: "Barnes Supply",
    category: "shopping",
    categoryLabel: "宠物与园艺用品",
    area: "ninth",
    coordinates: [36.010293, -78.9217344],
    address: "774 9th Street, Durham",
    summary: "Ninth Street 北端的本地宠物与园艺用品店。",
    facts: ["提供宠物食品、玩具与园艺用品", "停车位有限，步行或骑行更方便"],
    source: {
      label: "Discover Durham · Barnes Supply",
      url: "https://www.discoverdurham.com/directory/barnes-supply-co/",
      checkedAt: "2026-07-23",
    },
    confidence: "verified",
    markerLabel: "BS",
    previewEmoji: "🐾",
  },
  {
    id: "red-mango-wilson",
    name: "Red Mango · Wilson Recreation Center",
    shortName: "Red Mango",
    category: "food",
    categoryLabel: "校园餐饮 · 酸奶与果昔",
    area: "west",
    coordinates: [35.9969018, -78.9406545],
    address: "Wilson Recreation Center, 330 Towerview Road",
    summary: "Wilson Recreation Center 内的 Red Mango，适合运动后买酸奶、果昔和轻食。",
    facts: ["位于 Wilson Recreation Center", "开放时间以 Duke Campus Hours 当天信息为准"],
    source: {
      label: "Duke Campus Hours · Dining",
      url: "https://campushours.oit.duke.edu/places/dining",
      checkedAt: "2026-07-23",
    },
    confidence: "verified",
    markerLabel: "RM",
    previewEmoji: "🥭",
  },
  {
    id: "saladelia-perkins",
    name: "Saladelia @ The Perk",
    shortName: "Saladelia Perkins",
    category: "food",
    categoryLabel: "校园餐饮 · 咖啡与轻食",
    area: "west",
    coordinates: [36.003204, -78.938078],
    address: "Von der Heyden Pavilion, Perkins Library",
    summary: "Perkins / Bostock 连廊附近的咖啡与轻食点，适合自习期间买三明治、沙拉或饮料。",
    facts: ["提供咖啡、甜点、三明治、卷饼和沙拉", "营业时间通常短于图书馆开放时间"],
    source: {
      label: "Duke Libraries · Amenities",
      url: "https://library.duke.edu/using/amenities",
      checkedAt: "2026-07-23",
    },
    confidence: "verified",
    markerLabel: "SD",
    previewEmoji: "🥗",
  },
  {
    id: "mcdonalds-bryan",
    name: "McDonald's · Bryan Center",
    shortName: "McDonald's Bryan",
    category: "food",
    categoryLabel: "校园餐饮 · 快餐",
    area: "west",
    coordinates: [36.001109, -78.941488],
    address: "Bryan Center, 125 Science Drive",
    summary: "Bryan Center 内的快捷餐饮点，适合课间快速取餐。",
    facts: ["位于 Bryan Center", "开放时间以 Duke Campus Hours 当天信息为准"],
    source: {
      label: "Duke Campus Hours · Dining",
      url: "https://campushours.oit.duke.edu/places/dining",
      checkedAt: "2026-07-23",
    },
    confidence: "verified",
    markerLabel: "M",
    previewEmoji: "🍔",
  },
  {
    id: "trinity-cafe",
    name: "Trinity Cafe",
    shortName: "Trinity Cafe",
    category: "food",
    categoryLabel: "校园餐饮 · East 咖啡",
    area: "east",
    coordinates: [36.0075937, -78.9139503],
    address: "East Campus Union, 1324 Campus Drive",
    summary: "East Campus Union 内的咖啡与轻食点，适合一年级学生课间停留。",
    facts: ["与 Marketplace 同楼", "开放时间以 Duke Campus Hours 当天信息为准"],
    source: {
      label: "Duke Campus Hours · Dining",
      url: "https://campushours.oit.duke.edu/places/dining",
      checkedAt: "2026-07-23",
    },
    confidence: "verified",
    markerLabel: "TC",
    previewEmoji: "☕",
  },
  {
    id: "nan-xiang-express",
    name: "Nan Xiang Express & Tsaocha",
    shortName: "Nan Xiang Express",
    category: "food",
    categoryLabel: "Duke 周边餐饮 · 小笼包与奶茶",
    area: "essentials",
    coordinates: [36.005522, -78.9226205],
    address: "1605 Erwin Road, Durham",
    summary: "Blue Light Living 一层的上海点心与奶茶店，可搭乘 CSF 在 Blue Light 站下车。",
    facts: ["主打小笼包、生煎、面食与奶茶", "Blue Light Shuttle 站步行可达"],
    source: {
      label: "Discover Durham · Nan Xiang Express",
      url: "https://www.discoverdurham.com/directory/nan-xiang-express/",
      checkedAt: "2026-07-23",
    },
    confidence: "verified",
    markerLabel: "NX",
    previewEmoji: "🥟",
  },
  {
    id: "sushi-love",
    name: "Sushi Love",
    shortName: "Sushi Love",
    category: "food",
    categoryLabel: "Duke 周边餐饮 · 寿司",
    area: "essentials",
    coordinates: [36.0070336, -78.9472546],
    address: "2812 Erwin Road, Suite 204, Durham",
    summary: "Erwin Road 上靠近 Duke 医院一带的寿司与亚洲餐厅。",
    facts: ["菜单以寿司和日式餐点为主", "从 West Campus 骑行或驾车更方便"],
    source: {
      label: "Discover Durham · Sushi Love",
      url: "https://www.discoverdurham.com/directory/sushi-love/",
      checkedAt: "2026-07-23",
    },
    confidence: "verified",
    markerLabel: "SL",
    previewEmoji: "🍣",
  },
  {
    id: "naanstop-erwin",
    name: "NaanStop Indian Cuisine",
    shortName: "NaanStop",
    category: "food",
    categoryLabel: "Duke 周边餐饮 · 印度菜",
    area: "essentials",
    coordinates: [36.006925, -78.94716],
    address: "2812 Erwin Road, Durham",
    summary: "Erwin Road 上的印度餐厅，提供正餐、外带与分时段营业。",
    facts: ["午餐和晚餐之间可能暂停营业", "从 West Campus 骑行或驾车更方便"],
    source: {
      label: "Discover Durham · NaanStop",
      url: "https://www.discoverdurham.com/directory/naanstop-indian-cuisine/",
      checkedAt: "2026-07-23",
    },
    confidence: "verified",
    markerLabel: "NN",
    previewEmoji: "🍛",
  },
  {
    id: "enzos-pizza",
    name: "Enzo's Pizza Co.",
    shortName: "Enzo's Pizza",
    category: "food",
    categoryLabel: "Duke 周边餐饮 · 披萨",
    area: "essentials",
    coordinates: [36.0091759, -78.9444179],
    address: "2608 Erwin Road, Durham",
    summary: "Erwin Road 上靠近 Duke 的披萨店，适合外带、多人点餐或较晚用餐。",
    facts: ["提供披萨、沙拉与外带", "从 West Campus 骑行或驾车较方便"],
    source: {
      label: "Discover Durham · Enzo's Pizza",
      url: "https://www.discoverdurham.com/directory/enzos-pizza-co/",
      checkedAt: "2026-07-23",
    },
    confidence: "verified",
    markerLabel: "EZ",
    previewEmoji: "🍕",
  },
];

const SHUTTLE_SOURCE_URL =
  "https://duke.transloc.com/routes/23/stops";

export const PLACES: Place[] = [
  ...BASE_PLACES,
  ...SHUTTLE_STOPS.filter(
    (stop) =>
      stop.id !== "east-campus-statue-stop" &&
      stop.id !== "swift-300-shuttle-stop",
  ).map(
    (stop): Place => ({
      id: stop.id,
      name: `${stop.name} · Shuttle Stop`,
      shortName: stop.shortName,
      category: "transit",
      categoryLabel: "Shuttle 站点 · CSF",
      area: stop.area,
      coordinates: stop.coordinates,
      summary: `${SHUTTLE_ROUTE_NAME} 的官方站点；点位来自 Duke 当前 GTFS。`,
      facts: [
        stop.stopCode ? `站点编号：${stop.stopCode}` : "站点编号以 TransLoc 为准",
        "点击 Shuttle 导航可查看上车站、沿途站点和下车后步行",
      ],
      source: {
        label: "Duke Transit GTFS + TransLoc",
        url: SHUTTLE_SOURCE_URL,
        checkedAt: "2026-07-23",
      },
      confidence: "verified",
      markerLabel: "S",
      previewEmoji: "🚌",
      shuttle: {
        route: SHUTTLE_ROUTE_NAME,
        summary: "实时车辆、临时改道与停靠状态请查看 TransLoc。",
        liveUrl: "https://duke.transloc.com/",
      },
    }),
  ),
];

export const FALL_2026_PLAN = [
  {
    day: "周一 / 周三",
    items: [
      { time: "10:05", course: "GLHLTH 101", placeId: "social-sciences" },
      { time: "11:45", course: "KOREAN 101 · 备选", placeId: "languages" },
    ],
  },
  {
    day: "周二 / 周四",
    items: [
      { time: "08:30", course: "FIN ACCOUNTING 174", placeId: "french-science" },
      { time: "待确认", course: "MATH 333 / 431", placeId: "physics" },
    ],
  },
];

export const OFFICIAL_LINKS = [
  { label: "Duke 官方校园地图", url: "https://maps.duke.edu/" },
  {
    label: "Duke Transit 路线与通知",
    url: "https://parking.duke.edu/buses-vans/",
  },
  { label: "TransLoc 实时校车", url: "https://duke.transloc.com/" },
  { label: "GoTriangle 区域公交", url: "https://gotriangle.org/" },
  { label: "RDU 机场地面交通", url: "https://www.rdu.com/ground-transportation/" },
  {
    label: "Duke Dining 实时菜单",
    url: "https://students.duke.edu/living/dining/dining-locations/",
  },
  { label: "Discover Durham", url: "https://www.discoverdurham.com/" },
  { label: "Visit Raleigh", url: "https://www.visitraleigh.com/" },
  { label: "Duke ePrint 状态", url: "https://eprint.oit.duke.edu/" },
];
